In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace =True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.03992532, -1.01170589, -1.01286577, ..., -0.33121844,
         0.17024159,  0.65745641],
       [ 0.30983043,  2.33540685,  0.21577977, ..., -0.74542534,
         0.50814123, -1.22347504],
       [-0.10525575, -0.41134717, -0.16055074, ..., -0.36650553,
        -0.62612282, -0.79390293],
       ...,
       [-1.84948851,  1.34910323, -1.81808692, ..., -0.98395399,
        -0.19462657,  1.20536348],
       [-0.87156869, -0.52871053, -0.8547649 , ..., -0.3003233 ,
        -0.2104904 ,  1.7565126 ],
       [ 0.23145751, -0.56933631,  0.13925222, ..., -0.53400565,
        -0.61501813, -0.86576845]])

In [9]:
Y_train

426    B
414    M
483    B
443    B
102    B
      ..
35     M
46     B
539    B
507    B
434    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(Y_train)
y_test = encoder.transform(Y_test)

In [11]:
X_train_tensor = torch.tensor(X_train)
X_test_tensor = torch.tensor(X_test)
Y_train_tensor = torch.tensor(y_train)
Y_test_tensor = torch.tensor(y_test)

In [12]:
class MySimpleNN():
  def __init__(self,X):
    self.weights =torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad = True)
    self.bias = torch.zeros(1,dtype = torch.float64,requires_grad = True)

  def forward(self,X):
      z = torch.matmul(X_train_tensor,model.weights) + model.bias
      y_pred = torch.sigmoid(z)
      return y_pred

  def loss_function(self,y_pred,y):
    epsilon =1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -(Y_train_tensor*torch.log(y_pred)+(1 - Y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss




In [38]:
learning_rate = 0.1
epochs=100


In [39]:
#Create model
model = MySimpleNN(X_train_tensor)
model.weights

#forward pass

#loss calculation

# backward pass

#update parameters

for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)
  #loss calculation
  loss = model.loss_function(y_pred,Y_train_tensor)
  #backward
  loss.backward()
  #parameter updates
  with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad
  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss
  print(f"epoch: {epoch+1}, loss: {loss.item()}")



epoch: 1, loss: 3.21579913112471
epoch: 2, loss: 3.0717659076558173
epoch: 3, loss: 2.925777752612433
epoch: 4, loss: 2.7727911958810716
epoch: 5, loss: 2.618851866659118
epoch: 6, loss: 2.456066090514589
epoch: 7, loss: 2.284953584988575
epoch: 8, loss: 2.1171239649654514
epoch: 9, loss: 1.952448749753288
epoch: 10, loss: 1.7915694482758449
epoch: 11, loss: 1.6396776447980423
epoch: 12, loss: 1.4955100060042728
epoch: 13, loss: 1.3583925361574016
epoch: 14, loss: 1.2329627808085386
epoch: 15, loss: 1.1253385064612347
epoch: 16, loss: 1.0364851725186104
epoch: 17, loss: 0.9661683201422598
epoch: 18, loss: 0.9127798827524277
epoch: 19, loss: 0.8735719910331731
epoch: 20, loss: 0.8452704128399252
epoch: 21, loss: 0.8247631128446247
epoch: 22, loss: 0.8095450076915737
epoch: 23, loss: 0.7978304311191534
epoch: 24, loss: 0.7884455480684438
epoch: 25, loss: 0.7806519216337006
epoch: 26, loss: 0.7739909106752595
epoch: 27, loss: 0.7681742366548578
epoch: 28, loss: 0.763015084617998
epoch: 29

In [19]:
model.bias

tensor([-0.1231], dtype=torch.float64, requires_grad=True)

In [26]:
model.weights

tensor([[ 0.3324],
        [-0.0529],
        [ 0.2530],
        [-0.2439],
        [ 0.0738],
        [-0.3894],
        [ 0.2321],
        [-0.0232],
        [ 0.0186],
        [-0.0813],
        [ 0.3078],
        [ 0.1276],
        [-0.2709],
        [-0.1547],
        [ 0.0036],
        [ 0.0168],
        [ 0.0451],
        [ 0.0358],
        [-0.0157],
        [-0.0127],
        [ 0.0455],
        [-0.0470],
        [-0.2445],
        [ 0.0623],
        [ 0.1111],
        [ 0.2548],
        [-0.1819],
        [-0.1376],
        [ 0.0116],
        [ 0.1017]], dtype=torch.float64, requires_grad=True)

In [41]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")





Accuracy: 0.6578947305679321
