In [45]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [43]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [44]:
df.shape

(569, 33)

In [46]:
df.drop(columns=['id','Unnamed: 32'],inplace =True)

In [47]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [48]:
X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [49]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [50]:
X_train

array([[-0.20468924, -1.24168124, -0.2113799 , ...,  0.25837995,
         0.51952356,  0.51439943],
       [ 0.51888683,  0.91782509,  0.42070671, ..., -0.25180086,
         0.07164261,  0.02771623],
       [ 0.21526864, -0.41598764,  0.18028365, ...,  0.7602467 ,
         0.81971617, -0.69896748],
       ...,
       [ 1.81848619,  2.35043876,  1.95777037, ...,  2.24619555,
         1.90008851,  2.22614329],
       [-0.40331796,  2.3739628 , -0.45673471, ..., -0.77740047,
        -0.79682907, -1.06815622],
       [-0.78638765,  0.24503771, -0.61167402, ...,  2.13282204,
         5.99522942,  4.95468751]])

In [51]:
Y_train

482    B
10     M
138    M
146    M
1      M
      ..
474    B
509    M
567    M
552    B
3      M
Name: diagnosis, Length: 455, dtype: object

In [52]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(Y_train)
y_test = encoder.transform(Y_test)

In [64]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
Y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
Y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [86]:
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features);
    out = self.sigmoid(out)
    return out



In [87]:
learning_rate = 0.1
epochs=100


In [88]:
loss_fn = torch.nn.BCELoss()

In [94]:
#Create model
model = MySimpleNN(X_train_tensor.shape[1])

#optimiser
optimiser = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)
  #loss calculation
  loss = loss_fn(y_pred,Y_train_tensor.view(-1,1))


  #clear gradients
  optimiser.zero_grad()

  #backward
  loss.backward()
  #parameter updates
  optimiser.step()



  #print loss
  print(f"epoch: {epoch+1}, loss: {loss.item()}")



epoch: 1, loss: 0.8131210207939148
epoch: 2, loss: 0.7334955334663391
epoch: 3, loss: 0.6621137857437134
epoch: 4, loss: 0.5992331504821777
epoch: 5, loss: 0.5445040464401245
epoch: 6, loss: 0.4971650540828705
epoch: 7, loss: 0.45630601048469543
epoch: 8, loss: 0.4210139214992523
epoch: 9, loss: 0.3904586732387543
epoch: 10, loss: 0.3639170825481415
epoch: 11, loss: 0.3407687246799469
epoch: 12, loss: 0.32048699259757996
epoch: 13, loss: 0.3026285767555237
epoch: 14, loss: 0.28682342171669006
epoch: 15, loss: 0.27276456356048584
epoch: 16, loss: 0.26019802689552307
epoch: 17, loss: 0.2489139437675476
epoch: 18, loss: 0.23873893916606903
epoch: 19, loss: 0.2295295000076294
epoch: 20, loss: 0.22116619348526
epoch: 21, loss: 0.21354924142360687
epoch: 22, loss: 0.20659475028514862
epoch: 23, loss: 0.20023158192634583
epoch: 24, loss: 0.1943989247083664
epoch: 25, loss: 0.1890440434217453
epoch: 26, loss: 0.1841207593679428
epoch: 27, loss: 0.17958806455135345
epoch: 28, loss: 0.1754089891

In [97]:
model.linear.bias

Parameter containing:
tensor([-0.5040], requires_grad=True)

In [96]:
model.linear.weight

Parameter containing:
tensor([[ 0.4082,  0.3781,  0.4608,  0.2347,  0.1592,  0.1008,  0.4410,  0.1748,
          0.2667, -0.5942,  0.2942,  0.0702,  0.2801,  0.4301, -0.1673,  0.0304,
         -0.0768,  0.2530, -0.2272, -0.4929,  0.3307,  0.5535,  0.2139,  0.5444,
          0.5271,  0.1553,  0.3709,  0.2513,  0.3727,  0.4179]],
       requires_grad=True)

In [99]:
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")





Accuracy: 0.6015697121620178
